### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by AndersonHJB** [zkcpku/OnlinePythonTutor_for_js#1]
![image](https://user-images.githubusercontent.com/48122016/137247979-bebb12b3-e7f5-490c-94f3-91ee196f8947.png)

**Comment by zkcpku** [comment]
hello
`$1`的部分需要替换成待分析的js文件路径，如`test_demo\data-types.js`
希望可以帮到您

**Comment by zkcpku** [comment]
If you have any questions, feel free to re-open it.
